godkendte_indsatser = {
    indsats.lower() for indsats in [
        "medicindispensering",
        "medicinadministration",
        "akutindsats SUL § 138",
        "Anlæggelse og pleje af kateter",
        "Behandling med ortopædiske hjælpemidler",
        "Behandling og pleje af hudproblem",
        "Behandling og pleje af mave-tarmproblem",
        "Cirkulationsbehandling",
        "Dialyse",
        "Drænpleje",
        "Ernæringsindsats",
        "Forflytning og mobilisering",
        "Inkontinensbehandling",
        "Iltbehandling",
        "Intravenøs væskebehandling",
        "Intravenøs medicinsk behandling",
        "Intravenøs medicinsk behandling med pumpe",
        "kompressionsbehandling",
        "antabus",
        "Creme",
        "insulin",
        "inhalation",
        "injektion",
        "laksantia",
        "medicinsk tandpasta",
        "medicinske plastre",
        "medicinsk neglelak",
        "medicinsk shampoo",
        "næsespray",
        "PN medicin",
        "subkutan nål",
        "suppositorie",
        "udlevering af forhåndsdispenseret medicin",
        "vagitorie",
        "øjendråber/salver",
        "øredrypning",
        "Dosisdispensering",
        "kontakt læge/apotek vedr. medicin",
        "opfølgning på medicinsk behandling",
        "opstart af dosispakket medicin",
        "nonfarmakologisk smertelindring",
        "oplæring",
        "parenteral ernæring",
        "personlig pleje",
        "pleje ved anvendelse af personlige hjælpemidler",
        "psykiatrisk pleje",
        "psykisk støtte",
        "rehabilitering",
        "respirationsbehandling",
        "respiratorbehandling",
        "samarbejde med netværk",
        "sekretsugning",
        "sondeernæring",
        "stomipleje",
        "subkutan væskebehandling",
        "supplerende udredning",
        "særlig kommunikationsform",
        "sårbehandling",
        "venøst sår",
        "traumesår",
        "blandingssår",
        "arterielt sår",
        "tryksår",
        "cancersår",
        "diabetisk sår",
        "kirurgisk sår",
        "telesår-diabetiske sår",
        "telesår-venøse",
        "telesår-blandingssår",
        "trakeostomipleje",
        "undersøgelse og måling af værdier",
        "vejledning",
        "væske per os"
    ]
}
