godkendte_organisationer = [
    # "Benediktsgruppen",
    "Fruens Bøgegruppen",
    # "Hunderupgruppen",
    # "Kalørgruppen",
    # "Lavsengruppen",
    "Lindvedgruppen",
    # "Munkebjerggruppen",
    # "Mågebakkegruppen",
    # "Næsbygruppen",
    # "Rosengårdsgruppen",
    # "Skibhusgruppen",
    # "Skt. Hansgruppen",
    # "Stadiongruppen",
    # "Stenløkkegruppen",
    # "Tagtækkergruppen",
    # "Åsumgruppen",
    # "Aftengruppen Risingsvej",
    # "Aftengruppen Syd-Øst",
    # "Aftengruppen Lavsenvænget",
    # "Aftengruppen Syd-Vest",
    # "Sundhedsklinik Bolbro",
    # "Sundhedsklinik Dalum",
    # "Sundhedsklinik Havebæk",
    # "Sundhedsklinik VIVO",
    # "Sundhedsklinik Ørbækvej",
    # "Akutteamet",
    # "Aftensygeplejen Nord",
    # "Hunderupgruppen Aftensygepleje",
]
