approved_organizations = [
    "Benediktsgruppen",
    "Fruens Bøgegruppen",
    "Hunderupgruppen",
    "Kalørgruppen",
    "Lavsengruppen",
    "Lindvedgruppen",
    "Munkebjerggruppen",
    "Mågebakkegruppen",
    "Næsbygruppen",
    "Rosengårdsgruppen",
    "Skibhusgruppen",
    "Skt. Hansgruppen",
    "Stadiongruppen",
    "Stenløkkegruppen",
    "Tagtækkergruppen",
    "Åsumgruppen",
    "Aftengruppen Risingsvej",
    "Aftengruppen Syd-Øst",
    "Aftengruppen Lavsenvænget",
    "Aftengruppen Syd-Vest",
    "Sundhedsklinik Bolbro",
    "Sundhedsklinik Dalum",
    "Sundhedsklinik Havebæk",
    "Sundhedsklinik VIVO",
    "Sundhedsklinik Ørbækvej",
    "Akutteamet",
    "Stadiongruppen Aftensygepleje",
    "Hunderupgruppen Aftensygepleje",
    "Natgruppen Område 1 - Udkørende",
    "Servicegruppen Nord",
    "Servicegruppen Syd",
    "Flenco Rengøring ApS",
    "Cenema Service ApS",
    "JJS Rent",
    "Danren Hjemmeservice A/S",
    "Skibhus Rengøring og Vinduespolering",
    "Svanepleje, Syd-Nat",
    "Svane Pleje, Syd-Dag",
    "Svane Pleje, Syd-Aften",
    "Svane Pleje, Syd ApS",
    "Svane Pleje, Syd + Munkebjerggruppen sygepleje",
    "Benediktsgruppen Træning",
    "Fruens Bøgegruppen Træning",
    "Hunderupgruppen Træning",
    "Kalørgruppen Træning",
    "Lavsengruppen Træning",
    "Lindvedgruppen Træning",
    "Munkebjerggruppen Træning",
    "Mågebakkegruppen Træning",
    "Næsbygruppen Træning",
    "Rosengårdsgruppen Træning",
    "Skibhusgruppen Træning",
    "Skt. Hansgruppen Træning",
    "Stadiongruppen Træning",
    "Stenløkkegruppen Træning",
    "Tagtækkergruppen Træning",
    "Åsumgruppen Træning"
]
